name: build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn build